# Site settings
title: Niramay Vaidya' personal website
email: niramay.vaidya@gmail.com
url: https://github.com/NiramayVaidya
description: "My own personal website highlighting my work at CoEP as an undergraduate IT engineering student"
keywords: "College of Engineering, Pune (CoEP), Information Technology (IT)"
skills: "System Programming, Computing Systems Architecture"
meta_author: Vaidya Niramay

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  location: Location
  social: Around the Web
  credits: Credits
  last_updated: November 16, 2021

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
